repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0  # Use the ref you want to point at
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: requirements-txt-fixer
      - id: pretty-format-json
        args: ['--autofix']
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
    rev: v0.0.278
    hooks:
      - id: ruff